trigger:
- main
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  buildDirectory: 'dist'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - script: |
        npm run lint
      displayName: 'Run linting'
      continueOnError: true

    - script: |
        npm run build
      displayName: 'Build application'
      env:
        VITE_FIREBASE_API_KEY: $(VITE_FIREBASE_API_KEY)
        VITE_FIREBASE_AUTH_DOMAIN: $(VITE_FIREBASE_AUTH_DOMAIN)
        VITE_FIREBASE_PROJECT_ID: $(VITE_FIREBASE_PROJECT_ID)
        VITE_FIREBASE_STORAGE_BUCKET: $(VITE_FIREBASE_STORAGE_BUCKET)
        VITE_FIREBASE_MESSAGING_SENDER_ID: $(VITE_FIREBASE_MESSAGING_SENDER_ID)
        VITE_FIREBASE_APP_ID: $(VITE_FIREBASE_APP_ID)
        VITE_FIREBASE_MEASUREMENT_ID: $(VITE_FIREBASE_MEASUREMENT_ID)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(buildDirectory)'
        artifactName: 'webapp'
        publishLocation: 'Container'
      displayName: 'Publish build artifacts'

- stage: Deploy
  displayName: 'Deploy to Server'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy via FTP'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'webapp'
              downloadPath: '$(System.ArtifactsDirectory)'
            displayName: 'Download build artifacts'

          - task: FtpUpload@2
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: '$(FTP_SERVICE_CONNECTION)'
              rootDirectory: '$(System.ArtifactsDirectory)/webapp'
              filePatterns: '**'
              remoteDirectory: '$(FTP_REMOTE_DIRECTORY)'
              clean: true
              cleanContents: false
              preservePaths: true
              trustSSL: false
            displayName: 'Upload files via FTP'