# Simple Azure DevOps Pipeline for FTP Deployment
# Use this if you prefer a simpler single-stage approach

trigger:
- main
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build application'
  env:
    VITE_FIREBASE_API_KEY: $(VITE_FIREBASE_API_KEY)
    VITE_FIREBASE_AUTH_DOMAIN: $(VITE_FIREBASE_AUTH_DOMAIN)
    VITE_FIREBASE_PROJECT_ID: $(VITE_FIREBASE_PROJECT_ID)
    VITE_FIREBASE_STORAGE_BUCKET: $(VITE_FIREBASE_STORAGE_BUCKET)
    VITE_FIREBASE_MESSAGING_SENDER_ID: $(VITE_FIREBASE_MESSAGING_SENDER_ID)
    VITE_FIREBASE_APP_ID: $(VITE_FIREBASE_APP_ID)
    VITE_FIREBASE_MEASUREMENT_ID: $(VITE_FIREBASE_MEASUREMENT_ID)

- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: '$(FTP_SERVICE_CONNECTION)'
    rootDirectory: 'dist'
    filePatterns: '**'
    remoteDirectory: '$(FTP_REMOTE_DIRECTORY)'
    clean: true
    cleanContents: false
    preservePaths: true
    trustSSL: false
  displayName: 'Deploy via FTP'